# Copyright (c) 2011 Richard Ian Taylor
#
#	This file is part of the iDroid Project 
#	(http://www.idroidproject.org/).

obj-$(CONFIG_CPU_S5L8930)			+= cpu.o time.o

obj-$(CONFIG_MACH_IPHONE_4)			+= mach-iphone4.o
obj-$(CONFIG_MACH_IPOD_TOUCH_4G)	+= mach-ipodtouch4g.o
