# Copyright (c) 2011 Richard Ian Taylor
#
#	This file is part of the iDroid Project 
#	(http://www.idroidproject.org/).

obj-y								+= irq.o timer.o power.o clock.o dma.o gpio.o i2c.o
obj-y								+= spi.o usb.o vfl.o ftl.o nand.o pcf50633.o suspend.o

obj-$(CONFIG_MACH_IPHONE_2G)		+= mach_iphone2g.o
obj-$(CONFIG_MACH_IPHONE_3G)		+= mach_iphone3g.o
obj-$(CONFIG_MACH_IPOD_TOUCH_1G)	+= mach_ipodtouch1g.c
