# Copyright (c) 2011 Richard Ian Taylor
#
#	This file is part of the iDroid Project 
#	(http://www.idroidproject.org/).

obj-y					:= dev-uart.o
obj-m					:=
obj-n					:=
obj-					:=

obj-$(CONFIG_S5L_IRQ)	+= irq.o


